### ISSUE TITLE
Authentication fails due to refresh_token expected to be in JWT format

### ISSUE THREAD

**Issue by dant89** [peering-manager/pyixapi#29]
https://github.com/peering-manager/pyixapi/blob/3b434d747ce8f2566066788feebb8c4858a54931/pyixapi/core/api.py#L138

For LINX, we return `refresh_token` as a string so when this line tries to parse it as a JWT, it fails with: `pyixapi.core.token.TokenException: Not enough segments`

Is there anyway to make this more flexible as the schema doesn't enforce this value being in JWT format?

If I change it locally to `self.refresh_token = r["refresh_token"]`, this works fine.

**Comment by gmazoyer** [comment]
I thought it was always supposed to be JWT hence no fallback existing right now.

Maybe there is a way to inspect if the format is JWT before trying to set value. As a quick workaround, we could also catch the raised exception like so:

```python
try:
    self.refresh_token = Token.from_jwt(r["refresh_token"])
except TokenException:
    self.refresh_token = r["refresh_token"]
```

**Comment by gmazoyer** [comment]
@dant89 do you have a capture or an idea how LINX perform auth for their IX-API instance?

**Comment by dant89** [comment]
This was an implementation issue on our side, the ix-api schema states the JWT authentication responses should always be in JWT format.
